"""empty message

Revision ID: 4c896969aa10
Revises: 
Create Date: 2023-06-28 22:31:27.666468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c896969aa10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('miles_per_gallon', sa.Float(), nullable=True),
    sa.Column('cylinders', sa.Integer(), nullable=True),
    sa.Column('displacement', sa.Float(), nullable=True),
    sa.Column('horsepower', sa.Float(), nullable=True),
    sa.Column('weight_in_lbs', sa.Float(), nullable=True),
    sa.Column('acceleration', sa.Float(), nullable=True),
    sa.Column('year', sa.String(length=255), nullable=True),
    sa.Column('origin', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
